# RENAME A TABLE
ALTER TABLE users
RENAME TO new_name_users;

# RENAME A COLUMN
ALTER TABLE users
CHANGE LastName LastNames VARCHAR(100);

# MODIFY COLUMNS
ALTER TABLE users
MODIFY LastName CHAR(50) NOT NULL;

# ADD COLUMNS
ALTER TABLE users
ADD Website VARCHAR(100) NULL;

# ADD CONSTRAINTS (RESTRICTIONS)
ALTER TABLE users
ADD CONSTRAINT uq_email UNIQUE(email);

# DELETE A COLUMN
ALTER TABLE users
DROP website;